version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:

